### ISSUE TITLE
Allow access to http://jenkins/github-webhook/ by GitHub

### ISSUE THREAD

**Issue by GromNaN** [mocleiri/github-oauth-plugin#1]
After enableling the plugin, the URL http://jenkins/github-webhook/ become unaccessible for unauthentificated users. But this address is automatically called by GitHub when I push to my repository.

Is it possible to disable security on this path or allow explicitely github.com ?

Thanks for you excellent plugin.

**Comment by mocleiri** [comment]
This is sort of like this ticket in the JIRA: https://issues.jenkins-ci.org/browse/JENKINS-10495

Except it is for the github-plugin post-commit hook instead of the job build token.

I will see what can be done to link into the github-plugin and/or create a way to manually specify a list of urls that should allow anonymous reads.

Thanks for reporting this issue.

**Comment by mocleiri** [comment]
I've added a new boolean option to allow anonymous READ's for the github-webhook url to the Authorization Strategy.

(it will clear the values you entered for your authorization strategy so you may want a screen shot before doing this)  

Can you try with the 0.3-SNAPSHOT from here: 
http://ci.jenkins-ci.org/view/Plugins/job/plugins_github-oauth/org.jenkins-ci.plugins$github-oauth/lastSuccessfulBuild/artifact/org.jenkins-ci.plugins/github-oauth/0.3-SNAPSHOT/github-oauth-0.3-SNAPSHOT.hpi

If it works for you I will cut a 0.3 release for this feature.

I tested with a GET request and it does allow it but I am not setup right now to have github push into my test jenkins to see if it works for the POST request.

It should work by just copying in the *.hpi into the $JENKINS_HOME/plugins directory and then restarting jenkins.

Thanks

**Comment by GromNaN** [comment]
Thanks. I'm going to try that right now.

**Comment by GromNaN** [comment]
I've modified the .hpi file. The new option is there, but my "Github Authorization Settings" are not saved anymore.

**Comment by mocleiri** [comment]
This looks like a serialization problem.  I will dig into it and update you when the next snapshot is ready for testing

**Comment by bk-mz** [comment]
Are there any news on this issue?

**Comment by mocleiri** [comment]
i am slammed at work right now and probably won't have any free time until mid September.  If someone can fix the serialization issue in master I can do the new release.

The feature is in but the serialization issue is preventing the new AuthorizationStrategy instance from being used.

**Comment by vkravets** [comment]
Waiting the fix of this issue in the relese of 0.3

Thanks a lot for such plugin

**Comment by mocleiri** [comment]
Hi, 

I moved some files around and broke the jelly linkage between the form data and the authorization strategy/ACL.

So there wasn't a serialization bug exactly, although it looked like a serialization issue I saw before.

I've just commited my code and this feature is now testable in the 0.3 release.

I think it should work but I didn't test it with github doing the push (I just browsed to the url in an unauthenticated browser and could see jenkins vs nothing with the box unchecked).

The 0.3 release should propagate within 24 hours and be testable through the automatic update.

The ondisk format has changed and it should warn but backing up the settings before hand would be a good idea.

**Comment by vkravets** [comment]
It seems hooks are still not working if Jenkins is installed to non ROOT. E.g. http://hostname.com/jenkins/github-webhook or http://hostname.com/subfolder/jenkins/github-webhook

**Comment by vkravets** [comment]
May be add the parameter for this address/match?

**Comment by mocleiri** [comment]
I don't think its working either after testing on a public server.  I will add some logging and broaden the criteria.  

It could also be a permission issue, I granted READ on the url but maybe when its a post coming in there is a different permission that is needed.

**Comment by vkravets** [comment]
the regex is not correct. I will push new pull request now

**Comment by vkravets** [comment]
Read permission is working well for POST.

**Comment by vkravets** [comment]
fixed in 0.4 version

**Comment by bk-mz** [comment]
can't get 0.4 working. 

it fails jenkins initialization. i assume it cant reread existing projects configurations, but i still don't understand why it prevents jenkins start up.

WARNING: Skipping a non-existent type
com.thoughtworks.xstream.mapper.CannotResolveClassException: org.jenkinsci.plugins.GithubAuthorizationStrategy$GithubRequireOrganizationMembershipACL : org.jenkinsci.plugins.GithubAuthorizationStrategy$GithubRequireOrganizationMembershipACL
    at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:68)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:71)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:86)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:96)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at hudson.util.XStream2$CompatibilityMapper.realClass(XStream2.java:206)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at hudson.util.xstream.MapperDelegate.realClass(MapperDelegate.java:43)
    at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:38)
    at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:56)
    at hudson.util.RobustReflectionConverter.determineType(RobustReflectionConverter.java:358)
    at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:229)
    at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:180)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)
    at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:290)
    at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:233)
    at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:180)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:137)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:33)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:926)
    at hudson.util.XStream2.unmarshal(XStream2.java:89)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:912)
    at hudson.XmlFile.unmarshal(XmlFile.java:156)
    at jenkins.model.Jenkins$13.run(Jenkins.java:2328)
    at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
    at jenkins.model.Jenkins$5.runTask(Jenkins.java:796)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
hudson.util.IOException2: Unable to read d:\jenkins-drops\project\build.xml
    at hudson.XmlFile.unmarshal(XmlFile.java:160)
    at hudson.model.Run.reload(Run.java:283)
    at hudson.model.Run.<init>(Run.java:272)
    at hudson.model.AbstractBuild.<init>(AbstractBuild.java:159)
    at hudson.model.Build.<init>(Build.java:100)
    at hudson.model.FreeStyleBuild.<init>(FreeStyleBuild.java:41)
    at sun.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at hudson.model.AbstractProject.loadBuild(AbstractProject.java:947)
    at hudson.model.AbstractProject$1.create(AbstractProject.java:256)
    at hudson.model.AbstractProject$1.create(AbstractProject.java:254)
    at hudson.model.RunMap.load(RunMap.java:221)
    at hudson.model.AbstractProject.onLoad(AbstractProject.java:254)
    at hudson.model.Project.onLoad(Project.java:88)
    at hudson.model.Items.load(Items.java:115)
    at jenkins.model.Jenkins$14.run(Jenkins.java:2342)
    at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
    at jenkins.model.Jenkins$5.runTask(Jenkins.java:796)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: com.thoughtworks.xstream.converters.ConversionException: Cannot deserialize object with new readObject()/writeObject() methods
    at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doUnmarshal(SerializableConverter.java:281)
    at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:162)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)
    at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:290)
    at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:233)
    at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:180)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)
    at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
    at hudson.util.RobustCollectionConverter.populateCollection(RobustCollectionConverter.java:85)
    at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:61)
    at hudson.util.RobustCollectionConverter.unmarshal(RobustCollectionConverter.java:76)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)
    at hudson.util.RobustReflectionConverter.unmarshalField(RobustReflectionConverter.java:290)
    at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:233)
    at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:180)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:82)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:63)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:76)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:60)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:137)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:33)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:926)
    at hudson.util.XStream2.unmarshal(XStream2.java:89)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:912)
    at hudson.XmlFile.unmarshal(XmlFile.java:156)
    ... 24 more
11.09.2011 14:35:58 jenkins.model.Jenkins$6 onAttained
INFO: Loaded all jobs
11.09.2011 14:35:58 jenkins.model.Jenkins$6 onTaskFailed
SEVERE: Failed Finalizing set up
java.lang.NullPointerException
    at hudson.model.AbstractItem.hasPermission(AbstractItem.java:409)
    at jenkins.model.Jenkins.getItems(Jenkins.java:1256)
    at jenkins.model.Jenkins.getItems(Jenkins.java:288)
    at jenkins.model.Jenkins.getAllItems(Jenkins.java:1297)
    at hudson.model.DependencyGraph.getAllProjects(DependencyGraph.java:107)
    at hudson.model.DependencyGraph.build(DependencyGraph.java:93)
    at jenkins.model.Jenkins.rebuildDependencyGraph(Jenkins.java:3308)
    at jenkins.model.Jenkins$15.run(Jenkins.java:2350)
    at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
    at jenkins.model.Jenkins$5.runTask(Jenkins.java:796)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Exception in thread "pool-2-thread-3" java.lang.NullPointerException
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:191)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
11.09.2011 14:35:58 hudson.WebAppMain$2 run
SEVERE: Failed to initialize Jenkins
org.jvnet.hudson.reactor.ReactorException: java.lang.NullPointerException
    at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:246)
    at jenkins.model.Jenkins.executeReactor(Jenkins.java:814)
    at jenkins.model.Jenkins.<init>(Jenkins.java:728)
    at hudson.model.Hudson.<init>(Hudson.java:81)
    at hudson.model.Hudson.<init>(Hudson.java:77)
    at hudson.WebAppMain$2.run(WebAppMain.java:217)
Caused by: java.lang.NullPointerException
    at hudson.model.AbstractItem.hasPermission(AbstractItem.java:409)
    at jenkins.model.Jenkins.getItems(Jenkins.java:1256)
    at jenkins.model.Jenkins.getItems(Jenkins.java:288)
    at jenkins.model.Jenkins.getAllItems(Jenkins.java:1297)
    at hudson.model.DependencyGraph.getAllProjects(DependencyGraph.java:107)
    at hudson.model.DependencyGraph.build(DependencyGraph.java:93)
    at jenkins.model.Jenkins.rebuildDependencyGraph(Jenkins.java:3308)
    at jenkins.model.Jenkins$15.run(Jenkins.java:2350)
    at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:146)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:259)
    at jenkins.model.Jenkins$5.runTask(Jenkins.java:796)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:187)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:94)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by mocleiri** [comment]
can you retry with 0.5.  There was a problem in the regex with 0.4 but your problem looks different.

I think you have to reenter the values if coming from pre 0.3

**Comment by bk-mz** [comment]
Ok, 0.4 is finally working (had to kill 0.2 and install 0.4 from scratch). But somehow i managed to kill it again:

Exception: 
Stacktrace:

java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*/github-webhook/?$
^
    at java.util.regex.Pattern.error(Unknown Source)
    at java.util.regex.Pattern.sequence(Unknown Source)
    at java.util.regex.Pattern.expr(Unknown Source)
    at java.util.regex.Pattern.compile(Unknown Source)
    at java.util.regex.Pattern.(Unknown Source)
    at java.util.regex.Pattern.compile(Unknown Source)
    at java.util.regex.Pattern.matches(Unknown Source)
    at java.lang.String.matches(Unknown Source)
    at org.jenkinsci.plugins.GithubRequireOrganizationMembershipACL.hasPermission(GithubRequireOrganizationMembershipACL.java:91)

**Comment by bk-mz** [comment]
as i can see this is happening only when i choose "Github Commiter Authorization Strategy" in Authorization block.

**Comment by mocleiri** [comment]
In 0.4 there was a bug in the regex that failed with the error you just posted.  All anonymous requests passed through the ACL encounter the regex test on the URI which is why you see the error message.

Can you upgrade to version 0.5 and tell me if it works for you? 

Thanks.

**Comment by hedgehog** [comment]
just a comment to be notified about this issue.

**Comment by brandonbloom** [comment]
https://skitch.com/brandonbloom/f6epq/1-allow-access-to-http-jenkins-github-webhook-by-github-issues-mocleiri-github-oauth-plugin-github

**Comment by mocleiri** [comment]
This feature works in the 0.5 release.

I am closing this issue.

**Comment by bk-mz** [comment]
confirmed 0.6 version, feature is working.

thanks! :-D
